### ISSUE TITLE
[UI] Main Menu

### ISSUE THREAD

**Issue by owencooke** [owencooke/RQMO12#10]
Need a visually appealing main menu. 

THOUGHT 🤔 maybe include a Zebra? It's the rare disease mascot

**Comment by siddhantgoel7** [comment]
Main Menu: "Quest for the Cure"

Background:
The main menu background depicts a bustling cityscape with vibrant colors and dynamic movement, reflecting the energy and diversity of the game world. The skyline is adorned with iconic landmarks, while pedestrians and vehicles animate the scene, adding a sense of life and activity.

Title:
The game's title, "Quest for the Cure," is prominently displayed in bold, stylized font at the center of the screen. The text is infused with bright, contrasting colors that stand out against the backdrop, evoking a sense of optimism and determination.

Interactive Elements:

Character Selection:

Players can choose their character by selecting from a lineup of avatars representing rare disease patients, medical practitioners, and advocates. Each avatar is distinct in appearance, reflecting the diversity of characters in the game.
Hovering over each avatar displays a brief description of the character's role and abilities, helping players make an informed choice.
Navigation Buttons:

Beneath the character selection, a series of sleek, modern buttons offer intuitive navigation options such as "Play," "Settings," "Credits," and "Exit." Each button features subtle animations upon hover, enhancing user engagement.
Progress Bars:

Along the side of the screen, progress bars or battery indicators visually represent the player's advancement in fulfilling RQMO's core values. Each bar corresponds to a specific value, such as "Information & Support," "Awareness & Advocacy," "Research & Collaboration," and "Wellness & Resilience."
As players complete mini-games and challenges throughout the game, the progress bars gradually fill up, providing a sense of achievement and progress.
Thematic Accents:

Medical Symbols:

Throughout the main menu, subtle medical symbols and motifs are incorporated into the design, such as stethoscopes, DNA helices, and caduceus symbols. These elements reinforce the game's healthcare theme and tie into the quest for medical solutions.
Color Palette:

The color palette is carefully curated to evoke feelings of hope, vitality, and unity. Bright, uplifting colors like teal, coral, and sunshine yellow dominate the scene, creating a welcoming and optimistic atmosphere.
Dynamic Elements:

Subtle Animations:

To enhance visual interest, the main menu features subtle animations and parallax effects that add depth and dimension to the scene. For example, clouds drift lazily across the sky, while twinkling lights illuminate the cityscape below.
Interactive Sound Design:

Ambient sounds of city life, such as bustling traffic, distant chatter, and chirping birds, immerse players in the urban environment. Soft, melodic tunes play in the background, setting a soothing yet uplifting tone for the menu experience.

**Comment by siddhantgoel7** [comment]
Main Menu: "Quest for the Cure"

Background: The main menu background depicts a bustling cityscape with vibrant colors

Title: The game's title, "Quest for the Cure," is prominently displayed in bold, stylized font at the center of the screen.


Creating a visually appealing main menu requires a balance of aesthetics, functionality, and thematic relevance. Here's a concept for a main menu that incorporates elements of the game's storyline and core values:


Background:
The main menu background depicts a bustling cityscape with vibrant colors and dynamic movement, reflecting the energy and diversity of the game world. The skyline is adorned with iconic landmarks, while pedestrians and vehicles animate the scene, adding a sense of life and activity.

Title:
The game's title, "Quest for the Cure," is prominently displayed in bold, stylized font at the center of the screen. The text is infused with bright, contrasting colors that stand out against the backdrop, evoking a sense of optimism and determination.

Interactive Elements:

Character Selection:

Players can choose their character by selecting from a lineup of avatars representing rare disease patients, medical practitioners, and advocates. Each avatar is distinct in appearance, reflecting the diversity of characters in the game.
Hovering over each avatar displays a brief description of the character's role and abilities, helping players make an informed choice.
Navigation Buttons:

Beneath the character selection, a series of sleek, modern buttons offer intuitive navigation options such as "Play," "Settings," "Credits," and "Exit." Each button features subtle animations upon hover, enhancing user engagement.
Progress Bars:

Along the side of the screen, progress bars or battery indicators visually represent the player's advancement in fulfilling RQMO's core values. Each bar corresponds to a specific value, such as "Information & Support," "Awareness & Advocacy," "Research & Collaboration," and "Wellness & Resilience."
As players complete mini-games and challenges throughout the game, the progress bars gradually fill up, providing a sense of achievement and progress
