### ISSUE TITLE
[UI] Help button on City/Hospital Scenes

### ISSUE THREAD

**Issue by owencooke** [owencooke/RQMO12#24]
- clicking button should open up pop-up that displays
    - player's goal (find doctor X)
    - game instructions (spacebar to talk, arrow keys to walk, shift to run)
- button should be similar to the home button in the Maze minigame scene (top right of screen)
![image](https://github.com/owencooke/RQMO12/assets/90405643/cb5c6cf0-9110-48d5-93e1-00db96dc44cd)

**Comment by nandiniparekh31** [comment]
Done
