### ISSUE TITLE
[Script] Entire storyline for the game

### ISSUE THREAD

**Issue by nandiniparekh31** [owencooke/RQMO12#9]

**Comment by siddhantgoel7** [comment]
Title: "Quest for the Cure"

Story Introduction:
Welcome to the world of "Quest for the Cure," where rare diseases cast their shadow over the lives of many. In this interactive journey, you'll embark on a quest to uncover the mysteries of rare ailments while upholding the core values of the Quebec Coalition of Orphan Diseases (RQMO). Your actions and decisions will shape the lives of those affected by these conditions, as you strive to offer support, raise awareness, advance knowledge, and promote communication between patients and researchers.

Plot:
You assume the role of a compassionate advocate dedicated to addressing the challenges faced by individuals with rare diseases. As you navigate through the city, you'll encounter a diverse cast of characters, each with their own struggles and aspirations. Your goal is to help them overcome obstacles, find answers, and ultimately, achieve a better state of wellness.

Gameplay Progression:

Choose Your Path:

Begin your journey by selecting your character: a rare disease patient, a medical practitioner, or a devoted advocate.
Each character offers a unique perspective and gameplay experience, allowing you to explore different aspects of the rare disease landscape.
Rare Disease Patients:

Embark on a quest-style adventure, navigating through challenges and obstacles as you seek diagnosis and treatment for your condition.
Interact with specialists from various medical fields, completing mini-games and tasks to unlock vital information and resources.
Earn progress towards RQMO's core values by demonstrating resilience, perseverance, and determination in the face of adversity.
Medical Practitioner:

Assume the role of a medical practitioner tasked with diagnosing and treating rare diseases, utilizing your knowledge and expertise to provide optimal care.
Engage in diagnostic challenges and treatment simulations, making critical decisions that impact patient outcomes.
Earn progress towards RQMO's core values by delivering compassionate care, promoting awareness, and fostering communication with patients and colleagues.
Advocate for Change:

Step into the shoes of an advocate dedicated to raising awareness and advancing knowledge about rare diseases.
Interview patients, caregivers, and researchers to gather insights and perspectives on the challenges faced by those affected by rare conditions.
Utilize your platform to amplify voices, share stories, and advocate for policies that support individuals with rare diseases.
Conclusion:
As you progress through "Quest for the Cure," you'll witness the transformative power of compassion, collaboration, and community. By upholding the core values of the Quebec Coalition of Orphan Diseases (RQMO), you'll make a tangible difference in the lives of those affected by rare diseases, offering hope, support, and encouragement along the way
